### ISSUE TITLE
Image support

### ISSUE THREAD

**Issue by DjakaTechnology** [ch4rl3x/HtmlText#11]
Hi thanks for the great library, it would be great if we able to show the image here as well

**Comment by everestkid** [comment]
Yes Image support would be great.

**Comment by ch4rl3x** [comment]
Images are currently not planned. I am not at all sure if images can be easily implemented with the current implementation.

**Comment by DjakaTechnology** [comment]
> Images are currently not planned. I am not at all sure if images can be easily implemented with the current implementation. This component is not supposed to be a renderer for HTML

Agreed with the complexity, I'm not sure how's the best way do have this capability.

I was comparing it with NSAttributedString in iOS which have capability to show image from html

**Comment by ch4rl3x** [comment]
I will close this issue. I don't see any valueable ways to implement these feature.

Feel free to make a  PR if you find a good way. Refere to this issue, even if it is closed.
