### ISSUE TITLE
Material dependency version

### ISSUE THREAD

**Issue by kaychyka17** [ch4rl3x/HtmlText#5]
Currently you have material dependency in _buildCompose.gradle_ like this:
  `  implementation "androidx.compose.material:material:$compose_version"`

which is wrong because compose version and material version is not the same. Currently compose version is 1.2.0 and materil is 1.6.1

**Comment by ch4rl3x** [comment]
It is not material. It is compose material.

https://developer.android.com/jetpack/androidx/releases/compose-material

**Comment by kaychyka17** [comment]
Oh, my mistake. For some reason when I updated this project from 1.2.0 to 1.3.0 nothing from Compose Material wasn't found in my project and I thought that would be the reason.

Now I see I need to add compose material dependency also in my project to work properly.

I apologise for the misunderstanding.
